name: Release CD

# Workflow này sẽ chạy khi có push vào nhánh main
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    name: Build APK & Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter với tính năng Caching tự động giúp tăng tốc độ build
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      # Cài đặt dependencies trước khi build
      - name: Install dependencies
        run: flutter pub get

      # Giải mã Keystore từ Secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # Build APK với các biến môi trường
      - name: Build APK
        run: flutter build apk --release
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      # Tự động tạo Tag version (VD: v1.0.1)
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Tạo Release và đính kèm APK
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
          files: build/app/outputs/flutter-apk/app-release.apk